# Generated by Django 5.0.1 on 2024-01-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_rename_category_blog_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Published", "Published")],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
